datasets:
  camera_motion_cls: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
      # Be careful not to append minus sign (-) before split to avoid itemizing
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train: /home/tom/Open-Sora-dev/tools/scoring/MA-LMM/data/camera_motion/6_motion_classes_500.csv
        val: /home/tom/Open-Sora-dev/tools/scoring/MA-LMM/data/camera_motion/6_motion_classes_100.csv
        test: /home/tom/Open-Sora-dev/tools/scoring/MA-LMM/data/camera_motion/6_motion_classes_20.csv
