datasets:
  camera_motion_cls: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
      # Be careful not to append minus sign (-) before split to avoid itemizing
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train: /home/tom/Open-Sora-dev/opensora/utils/camera_pose_utils/pose_traj_classes_2024-10-01_18-07-05.csv
        val: /home/tom/Open-Sora-dev/opensora/utils/camera_pose_utils/pose_traj_classes_2024-10-01_18-07-05.csv
        test: /home/tom/Open-Sora-dev/opensora/utils/camera_pose_utils/pose_traj_classes_2024-10-01_18-07-05.csv
