 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  scoring_cls: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: scoring/annotation/train.json
          storage: scoring/annotation/train.json
        val:
          url:  scoring/annotation/val.json
          storage:  scoring/annotation/val.json
        test:
          url:  scoring/annotation/test.json
          storage:  scoring/annotation/test.json
      videos:
        storage: scoring/frames
